name: start

on:
  workflow_dispatch:
    inputs:
      script-file:
        description: 'Script File'
        required: true
      part-count:
        description: 'Part Count'
        required: true

jobs:
  start-job:
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout to repo
        uses: actions/checkout@v2
      - name: login to azure cli
        uses: azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: start
        env:
          scriptFile: ${{ github.event.inputs.script-file }}
          partCount: ${{ github.event.inputs.part-count }}
          runId: ${{ github.run_id }}
        run: |
          ACR_PASSWORD=$(az acr credential show --name enpolatacr --query "passwords[0].value" --output tsv)
          docker login enpolatacr.azurecr.io --username enpolatacr --password ${ACR_PASSWORD}
          ./build.sh ${scriptFile} ${runId} 1

          docker run -dit enpolatacr.azurecr.io/k6:${runId}
